### ISSUE TITLE
ERROR: InstallationLookupFailed

### ISSUE THREAD

**Issue by dabvid** [libimobiledevice/ifuse#24] opened 2015-04-13 12:53 UTC
--documents APPID works fine for me, however trying to mount the sandbox root of an app with --container prints out the following: ERROR: InstallationLookupFailed
I'm on iOS 8.3

**Comment by kekiefer** [comment] 2015-04-13 21:46
Same problem, this looks like new behavior on 8.3

**Comment by kekiefer** [comment] 2015-04-13 22:36
This is a problem at a lower level than ifuse. When I tried to create a HouseArrestClient against `VendDocuments` I got the same error. For me, `VendContainer` worked OK so at least there is a suitable workaround.

**Comment by kekiefer** [comment] 2015-04-15 00:11
@dabvid apparently iOS 8.3 enforces new restrictions on document sharing: http://www.iclarified.com/48418/ios-83-blocks-file-manager-software-from-accessing-app-data
> We just figured out a solution to bring the sandbox access back **for those Apps that willing to**. Now sandbox access will only be available for Apps having "UIFileSharingEnabled" key set to true in their info.plist [ iPhoneOSKeys.html ] and the access is restricted to /Documents directory only.

**Comment by dabvid** [comment] 2015-04-15 07:22
Thanks @kekiefer  
Was suspecting it could be related to 8.3 but couldn't verify.

**Comment by dunhamsteve** [comment] 2015-04-22 17:37
In the past, I've used the `--container` functionality both for "forensics" (poking around to see how other apps work) and for development.  I've found that with 8.3,` --container` no longer works with app-store installed apps, but `--container` does still work with apps that are deployed via XCode and Ad-Hoc distribution.

**Comment by programmin1** [comment] 2015-11-06 07:50
What exactly is "container", and does this work if I upgrade my iOS from 8.3?

**Comment by dunhamsteve** [comment] 2015-11-06 17:49
The `--container` flag mounts the entire directory tree for an app, instead of just the Documents directory.  Previously, it could be used to poke around in various apps private data, databases, etc.  Now it only works for apps that you've written and installed yourself via Xcode.

**Comment by FunkyM** [comment] 2015-11-10 19:03
Closing as already answered in https://github.com/libimobiledevice/ifuse/issues/24#issuecomment-93119672 and further. It's not a bug in ifuse, Apple tightened Sandbox access restrictions. Only Apps with "UIFileSharingEnabled" can be accessed.

**Closed by FunkyM** 2015-11-10 19:03 UTC
Labels: question

**Comment by parkerlreed** [comment] 2016-02-16 17:45
So I have no way of getting a zip file to an old application I use :( Thanks Apple.

**Comment by programmin1** [comment] 2016-02-18 06:00
I don't think they blocked it on 9.2.1, _if the app supports iTunes-file-sharing_. See for example my writeup here http://tunesviewer.sourceforge.net/ios-transfer-made-easier/

**Comment by parkerlreed** [comment] 2016-02-18 15:21
From what I can tell it was blanket enabled for everything and then changed to only ones that request the permission. So for any older applications you're screwed. I even tried iFunbox on Windows and it said that the change made it so you have to be jailbroken to access these applications on 8.x+.

**Comment by parkerlreed** [comment] 2016-02-18 15:26
@programmin1 Arch's libimobiledevice doesn't seem to ship with python2 bindings. Is there a way to try this out?

**Comment by vizzah** [comment] 2016-03-22 21:45
So does it restrict access for '--container' flag or for '--documents' flag to? Because mine doesn't work for both. (iOS 9.0.1, libimobiledevice 1.2.0-1, ifuse 1.1.3)

**Comment by kikiwora** [comment] 2020-06-09 18:45
iOS 13. Both --container & --documents flag does not work
